
### Успешное добавление users 1
POST http://localhost:8080/admin/users
Accept: application/json
Content-Type: application/json

{
  "email": "ivan.petrov@practicummail.ru",
  "name": "Иван Петров"
}

### Успешное добавление
POST http://localhost:8080/
Accept: application/json
Content-Type: application/json



### Успешное получение всех записей
GET http://localhost:8080/admin/users?from=0&size=10
Accept: application/json
Content-Type: application/json

