
### Успешное добавление users 1
POST http://localhost:8080/admin/users
Accept: application/json
Content-Type: application/json

{
  "app": "ewm-main-service",
  "uri": "/events/2",
  "ip": "192.163.0.2",
  "timestamp": "2023-09-06 11:00:23"
}

### Успешное добавление записи 1
POST http://localhost:8080/
Accept: application/json
Content-Type: application/json

{
  "app": "ewm-main-service",
  "uri": "/events/1",
  "ip": "192.163.0.1",
  "timestamp": "2022-09-06 11:00:23"
}


### Успешное получение всех записей
GET http://localhost:8080/admin/users?from=0&size=10
Accept: application/json
Content-Type: application/json

